import { getAllTask } from "@/api/taskFetch";
import CreatedTaskComponent from "@/components/TaskComponents/CreatedTaskComponent";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";



export default function Home() {
  //Estados para las tareas
  const [tasks, setTasks] = useState([]); //Listado de tareas
  const [isCreating, setIsCreating] = useState(false); //Indica si se esta creando una tarea
  

  //Funcion para conseguir todas las tareas
  const getAllTasksAux = async () => {
    const tasksAux = await getAllTask();
    setTasks(tasksAux.data);
  };
  useEffect(() => {
    getAllTasksAux();
  }, []);

  //Funcion para abrir formulario de crear tarea
  const handlerCreateTask = () => {
    setIsCreating(true);
  };
  //Funcion para cerrar el formulario de crear tarea
  const closeTaskCreation = () => {
    setIsCreating(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <main className={styles.main}>
          <div className={styles.tasksList}>
              {(tasks.length > 0) (
                (tasks).map((task, index) =>{
                  <span>Tarea: {task.title}</span>,
                  <span>Completado: {task.completed} </span>
                })
              )}
          </div>
          <hr/>
          <div className={styles.homeActions}>
              {(!isCreating ? (
                <button
                className={styles.createButton}
                onclick={handlerCreateTask}
                >
                  Crear Tarea
                </button>
              ): (
                <CreatedTaskComponent 
                  setIsCreating={setIsCreating}
                  closeTaskCreation={closeTaskCreation}
                />
              ))}
          </div>
        </main>
        <footer className={styles.footer}>
          
        </footer>
      
    </>
  );
}
